version: '3.8'

services:
  # ==========================================
  # 1. BASE DE DATOS (PostgreSQL)
  # ==========================================
  db:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_DB: EstacDuoc  # Revisa que coincida con tu .env
      POSTGRES_USER: postgres      # Revisa que coincida con tu .env
      POSTGRES_PASSWORD: Heavensdoa1502! # Revisa que coincida con tu .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # ---- AGREGAR ESTO ----
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d EstacDuoc"]
      interval: 5s
      timeout: 5s
      retries: 5

  # ==========================================
  # 2. CEREBRO (Tu Proyecto Django - Raíz)
  # ==========================================
  backend:
    build: . 
    command: python manage.py runserver 0.0.0.0:8000
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    # ---- CAMBIAR DEPENDS_ON A ESTO ----
    depends_on:
      db:
        condition: service_healthy

  # ==========================================
  # 3. INTERFAZ (Tu Panel de React)
  # ==========================================
  frontend:
    build: ./frontend  # Entra a la carpeta frontend y usa su Dockerfile
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

  # ==========================================
  # 4. EL BUZÓN DE MENSAJES (Redis)
  # ==========================================
  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"

  # ==========================================
  # 5. EL COCINERO (Celery Worker - Ejecutor)
  # ==========================================
  celery_worker:
    build: .  # Usa el mismo código base que el backend
    command: celery -A Estacionamiento worker -l info
    restart: always
    depends_on:
      - db
      - redis
    env_file:
      - .env  # Necesita las mismas credenciales de BD que el backend

  # ==========================================
  # 6. EL GERENTE (Celery Beat - Reloj)
  # ==========================================
  celery_beat:
    build: .  # Usa el mismo código base que el backend
    command: celery -A Estacionamiento beat -l info
    restart: always
    depends_on:
      - db
      - redis
    env_file:
      - .env  # Necesita las mismas credenciales de BD que el backend

volumes:
  postgres_data: