# Generated by Django 6.0.1 on 2026-02-03 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True, verbose_name='RUT')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre Completo')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo')),
                ('ppu', models.CharField(blank=True, max_length=10, null=True, verbose_name='Patente (PPU)')),
            ],
            options={
                'verbose_name': 'Funcionario',
                'verbose_name_plural': 'Funcionarios',
            },
        ),
    ]
