# Generated by Django 6.0.2 on 2026-02-16 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0002_funcionario_usuario_sistema'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='destino',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Destino / Área de Visita'),
        ),
    ]
