# Generated by Django 6.0.2 on 2026-02-16 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0003_funcionario_destino'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='ppu',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Patente'),
        ),
    ]
