# Generated by Django 6.0.2 on 2026-02-16 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapaestacionamiento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registromovimiento',
            name='area',
            field=models.CharField(default=True),
        ),
    ]
