# Generated by Django 6.0.2 on 2026-02-16 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapaestacionamiento', '0002_registromovimiento_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='registromovimiento',
            name='ppu',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Patente'),
        ),
    ]
