# Generated by Django 6.0.2 on 2026-02-16 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapaestacionamiento', '0003_registromovimiento_ppu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registromovimiento',
            name='ppu',
        ),
    ]
