# Generated by Django 6.0.2 on 2026-02-17 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapaestacionamiento', '0004_remove_registromovimiento_ppu'),
    ]

    operations = [
        migrations.AddField(
            model_name='registromovimiento',
            name='tipo_salida',
            field=models.CharField(blank=True, choices=[('NORMAL', 'Salida Normal (Escáner)'), ('MANUAL', 'Liberación Manual (Admin/Guardia)'), ('FORZADA', 'Reubicación / Otro')], default='NORMAL', max_length=20, null=True),
        ),
    ]
