# Generated by Django 6.0.2 on 2026-02-18 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapaestacionamiento', '0006_registromovimiento_liberado_por'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConfiguracionSistema',
        ),
        migrations.RemoveField(
            model_name='lugar',
            name='ocupado',
        ),
        migrations.RemoveField(
            model_name='registromovimiento',
            name='activo',
        ),
        migrations.AlterField(
            model_name='registromovimiento',
            name='area',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Área de estacionamiento'),
        ),
        migrations.AlterField(
            model_name='registromovimiento',
            name='tipo_salida',
            field=models.CharField(blank=True, choices=[('NORMAL', 'Salida Normal (Escáner)'), ('MANUAL', 'Liberación Manual (Admin/Guardia)'), ('FORZADA', 'Reubicación / Otro')], max_length=20, null=True),
        ),
    ]
